version: "3.7"
services:

  app:
    build:
      args:
        user: jonathan
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    image: laraveldocker
    container_name: laraveldocker-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laraveldocker

  db:
    image: mariadb
    environment:
      MYSQL_USER: laraveldocker
      MYSQL_PASSWORD: laraveldocker
      MYSQL_DATABASE: laraveldocker
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    networks:
      - laraveldocker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - laraveldocker
      
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 8025
    networks:
      - laraveldocker

  nginx:
    image: nginx:alpine
    container_name: laraveldocker-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - laraveldocker

networks:
  laraveldocker:
    driver: bridge

volumes:
## persistent data volume for mysql data
  dbdata:
    driver: local