version: "3.7"
services:
  app:
    build:
      args:
        user: jonathan
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - 8080:80 
    image: laraveldocker
    container_name: laraveldocker-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laraveldocker

  db:
    image: mariadb
    environment:
      MYSQL_USER: laraveldocker
      MYSQL_PASSWORD: laraveldocker
      MYSQL_DATABASE: laraveldocker
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    networks:
      - laraveldocker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - laraveldocker
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025
    networks:
      - laraveldocker
networks:
  laraveldocker:
    driver: bridge

volumes:
## persistent data volume for mysql data
  dbdata:
    driver: local